#!/usr/bin/env node
// Copyright (c) 2026 ZEBRA BI informacijske rešitve d.d. Distributed under the terms in LICENSE at the repository root.
"use strict";
/**
 * Zebra BI report-authoring MCP server.
 *
 * Reads an unopened PBIP project and reports what is wrong with it. The rules come from
 * rules.json, which is generated from the same marked source as the public skill, so a rule's
 * wording cannot drift from the prose a customer reads.
 *
 * Three things about the response shape, each of which exists because of a specific failure:
 *
 *   1. `checked` is reported alongside `findings`. The PowerShell checker this replaces prints
 *      "PRE-FLIGHT: PASS" on an empty directory, because every layer of it is guarded by an
 *      `if` with no else. "Nothing was wrong" and "nothing was looked at" must not be the same
 *      answer.
 *   2. `notChecked` is always non-empty. Most of what breaks a Zebra report is invisible to a
 *      file reader: whether the numbers are right, whether the variance is comparable, whether
 *      the actuals cover the same window. A validator that stays quiet about its own blind
 *      spots converts a caught error into a confident one.
 *   3. There is a real exit path. The script had no exit code at all, so a caller had to parse
 *      text to find out whether anything failed.
 *
 * Zero dependencies. The MCP stdio transport is newline-delimited JSON-RPC 2.0, which is small
 * enough that adding an SDK would mean shipping node_modules inside a plugin to save very
 * little. It also never touches the network, and never writes to the customer's project.
 */

const fs = require("fs");
const path = require("path");

const PROTOCOL_VERSION = "2025-06-18";
const SERVER = { name: "zebra-bi-report-authoring", version: "0.1.0" };

// --- the rule catalogue -------------------------------------------------------------------
// Shipped beside the skill, generated by zbi-public-skill.py from the marked internal source.
// Read once at startup: a rule set that changes under a running server would make two calls
// disagree for no visible reason.

const RULES_PATH = path.join(
  __dirname, "..", "skills", "report-authoring", "rules.json"
);

function loadRules() {
  try {
    const raw = JSON.parse(fs.readFileSync(RULES_PATH, "utf8"));
    return Array.isArray(raw.rules) ? raw.rules : [];
  } catch (err) {
    // A missing catalogue is a broken install, not a clean report. Say so rather than
    // returning zero findings, which would read as a pass.
    return null;
  }
}

const { checkers } = require("./checkers.js");
const tmdl = require("./tmdl.js");
const enc = require("./encoders.js");
const wr = require("./writers.js");
const prof = require("./profile.js");
const propose = require("./propose.js");
const profSource = require("./profile-source.js");

// --- reading the project ------------------------------------------------------------------

function readJson(abs, rel) {
  const buf = fs.readFileSync(abs);
  const hadBom = buf.length >= 3 && buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf;
  const text = buf.toString("utf8").replace(/^\uFEFF/, "");
  let parsed = null, parseError = null;
  try { parsed = JSON.parse(text); } catch (e) { parseError = e.message; }
  return { abs, rel, text, parsed, parseError, hadBom };
}

function walk(dir, out = []) {
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    // A symlink to a FILE is not a file in this project. Directory symlinks were already skipped
    // deliberately, but `e.isDirectory()` is false for a symlinked file, so one placed inside the
    // tree was read from wherever it pointed. Same guard as tmdl.js. Corrected 2026-08-31.
    if (e.isSymbolicLink()) continue;
    if (e.isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
}

function resolveProject(projectPath) {
  const p = {
    files: new Map(), checked: [], problems: [], allFiles: [], visuals: [], pages: [],
    pbipFiles: [], pbirFiles: [], declaredPages: [], notCheckedExtra: [],
  };
  if (!projectPath || !fs.existsSync(projectPath)) {
    return { ...p, fatal: `No such directory: ${projectPath}` };
  }
  p.fatal = null;

  const entries = fs.readdirSync(projectPath, { withFileTypes: true });
  const pbip = entries.filter((e) => e.isFile() && e.name.endsWith(".pbip"));
  const reportDirs = entries.filter((e) => e.isDirectory() && e.name.endsWith(".Report"));
  const modelDirs = entries.filter((e) => e.isDirectory() && e.name.endsWith(".SemanticModel"));

  // Report every layer, including duplicates. The checker being replaced silently inspected
  // only the first .Report and .SemanticModel, so a multi-report project said nothing about it.
  p.checked.push(`${pbip.length} .pbip file(s)`);
  p.checked.push(`${reportDirs.length} .Report director(y|ies)`);
  p.checked.push(`${modelDirs.length} .SemanticModel director(y|ies)`);
  if (reportDirs.length > 1 || modelDirs.length > 1) {
    p.problems.push({
      code: "multiple-projects-in-one-directory", severity: "wont-open", location: projectPath,
      message: "This directory holds more than one report or model. Every check below ran "
             + "against the first of each, so the others were not inspected.",
    });
  }

  // ADDED 2026-08-05. With no .Report there is nothing for any report rule to read, and every
  // one of them returns no findings for that reason alone. Reporting `ok: true` there is the
  // instrument claiming success for having read nothing -- which is the same failure this file's
  // header calls out in the PowerShell it replaces, one level up: not "every layer optional" but
  // "no layer at all". It cost a real half-hour: a corpus harness staged 20 projects with directory
  // junctions, a junction answers isSymbolicLink() rather than isDirectory(), and the run
  // reported a clean 0 findings on all 20 templates. `checked` said `0 .Report` and nobody read
  // it, because `ok` said pass. So the honesty has to live in `ok`, not only in the counts.
  if (reportDirs.length === 0) {
    return { ...p, fatal:
        `No *.Report directory in ${projectPath}, so nothing was checked. Every report rule `
      + `needs one and would report no findings for that reason alone. If the path is right, `
      + `check it is not a symlink or a Windows directory junction: those are not directories `
      + `to this resolver and read as absent.` };
  }

  for (const f of pbip) {
    p.pbipFiles.push(readJson(path.join(projectPath, f.name), f.name));
  }

  if (reportDirs.length) {
    const base = path.join(projectPath, reportDirs[0].name);
    for (const abs of walk(base)) {
      if (!/\.(json|pbir)$/i.test(abs)) continue;
      const rel = path.relative(base, abs).split(path.sep).join("/");
      const f = readJson(abs, rel);
      p.allFiles.push(f);
      p.files.set(rel, f);
      if (f.parseError) {
        p.problems.push({
          code: "unparseable-json", severity: "wont-open", location: rel,
          message: `This file is not valid JSON, so Power BI Desktop will refuse the whole `
                 + `project. ${f.parseError}`,
        });
        continue;
      }
      if (rel.endsWith("definition.pbir")) {
        const byPath = f.parsed?.datasetReference?.byPath?.path;
        p.pbirFiles.push({
          ...f, byPath,
          byPathResolves: byPath ? fs.existsSync(path.resolve(base, byPath)) : true,
        });
        // Desktop validates the $schema URL against a PATTERN and refuses the whole project on a
        // mismatch -- "Expected '$schema' property ... to follow patterns" -- before it reads a
        // single page. A plausible URL with one extra path segment
        // (`.../report/definition/definitionProperties/...`) did exactly that on 2026-09-06 while
        // this validator said ok. Project-shape fact, same class as unparseable-json.
        // Only a PRESENT, non-matching value is a measured fault; an absent $schema has not been
        // put through a cold open and is not claimed here.
        const schemaUrl = f.parsed?.$schema;
        const PBIR_SCHEMA = /^https:\/\/developer\.microsoft\.com\/json-schemas\/fabric\/item\/report\/definitionProperties\/[12]\.\d+\.\d+\/schema\.json$/;
        if (typeof schemaUrl === "string" && !PBIR_SCHEMA.test(schemaUrl)) {
          p.problems.push({
            code: "pbir-schema-url-invalid", severity: "wont-open", location: rel,
            message: `definition.pbir's $schema is '${schemaUrl}', `
              + "and Power BI Desktop checks it against a pattern before it opens anything: it must be "
              + "https://developer.microsoft.com/json-schemas/fabric/item/report/definitionProperties/2.0.0/schema.json "
              + "(a 1.x.y or 2.x.y version). Anything else refuses the whole project with "
              + "\"Expected '$schema' property ... to follow patterns\".",
          });
        }
      } else if (/^definition\/pages\/[^/]+\/page\.json$/.test(rel)) {
        p.pages.push({ ...f, pageName: rel.split("/")[2] });
      } else if (/\/visuals\/[^/]+\/visual\.json$/.test(rel)) {
        p.visuals.push({
          ...f,
          name: f.parsed?.name ?? rel.split("/").slice(-2)[0],
          visualType: f.parsed?.visual?.visualType ?? "",
        });
      }
    }
    const pages = p.files.get("definition/pages/pages.json");
    if (pages && !pages.parseError) p.declaredPages = pages.parsed?.pageOrder ?? [];
    p.checked.push(`${p.pages.length} page(s)`, `${p.visuals.length} visual(s)`,
                   `${p.allFiles.length} report file(s) parsed`);

    // A report can legitimately have no visuals yet, so this is not a fault and not fatal. But
    // most of the catalogue reads visuals, so a green result here means far less than a green
    // result on a populated report, and the caller must not have to work that out from a count.
    if (p.visuals.length === 0) {
      p.notCheckedExtra.push("Anything about a visual: this report has none, so most of the "
        + "catalogue had nothing to read and stayed silent for that reason rather than because "
        + "your visuals are correct.");
    }
  }

  // The model layer. Everything above reads the report; these are the only facts that come
  // from the semantic model, and they are the two the plan calls commercially decisive.
  p.model = tmdl.readModel(projectPath);
  if (p.model.present && p.model.tables.length === 0) {
    // A model directory with nothing parsed out of it is not a model with no measures. Saying
    // "this has no scenario measures" here would be inferring absence from absence of evidence,
    // which is the one thing this tool is built not to do.
    p.checked.push(`${p.model.files.length} TMDL file(s), 0 tables parsed`);
    p.notCheckedExtra.push("The semantic model: no TMDL tables could be read, so nothing is "
      + "claimed about scenario measures or a marked date table.");
  } else if (p.model.present) {
    p.checked.push(`${p.model.files.length} TMDL file(s)`, `${p.model.tables.length} table(s)`);

    // Reported, never flagged. All 20 shipped templates sit at 1600 or 1601 and every one of
    // them opens, so a finding here would warn on correct reports. It matters for exactly one
    // thing: Desktop upgrades the model in memory to 1606 when it opens the project, so a
    // `file.reload/v1` against a file still saying 1600 is refused as a downgrade. Whoever is
    // about to use the fast path needs the number; nobody needs a warning about it.
    if (p.model.compatibilityLevel !== null) {
      p.checked.push(
        `model compatibilityLevel: ${p.model.compatibilityLevel}`
        + (p.model.compatibilityLevel < 1606
            ? " (Desktop raises this to 1606 in memory on open, so reload is refused as a "
              + "downgrade until database.tmdl says 1606 — this is not a fault in the model)"
            : ""));
    }


    // Same shape as compatibilityLevel above, same reason: a FACT the caller needs at the moment
    // it reloads, not a defect. A `cultures/` file makes `file.reload/v1` die while the project
    // cold-opens perfectly, so the symptom is "the fast loop stopped working" with nothing on
    // screen naming the cause. It cost seven cold opens on 2026-08-15 before anyone connected the
    // two. Not a finding: the file is legitimate and Desktop is happy with it.
    if (p.model.cultureFiles && p.model.cultureFiles.length) {
      p.checked.push(
        `${p.model.cultureFiles.length} cultures/ file(s) — file.reload/v1 will not work on this `
        + `project (it cold-opens normally). Budget a cold open per iteration, or remove the `
        + `cultures file if nothing needs it.`);
    }
    const sc = tmdl.scenarioMeasures(p.model);
    const dt = tmdl.dateTable(p.model);

    // Not rules from the held catalogue. These are project-shape facts, the same class as
    // unparseable-json above, and nothing else in the plugin can see them.
    //
    // NARROWED 2026-08-15. `scenarioMeasures` recognises a scenario by NAME (ac/actual, pl/plan/
    // budget, py/previous year, fc/forecast) plus a base-measure test. That is a naming convention,
    // and a legitimate report can carry none of those names: the documented fallback for a dataset
    // with no scenario column and no date column is BENCHMARK-VS-POPULATION -- bind the sliced
    // measure to `Values` and an ALL() population measure to `Plan`, and the variance column reads
    // "how far this band sits from everyone". Measures called `Avg Score` and `Population Avg` are
    // exactly that, and the rule fired on a report that WAS a working variance report.
    //
    // So look at the report before claiming a variance is impossible: if any visual actually binds
    // a comparison well, the premise is refuted by the file in front of us. This can only ever
    // SUPPRESS a finding, never add one, so it cannot introduce a false positive of its own.
    const bindsAComparison = [...p.files.values()].some((f) => {
      const qs = f.parsed?.visual?.query?.queryState;
      if (!qs) return false;
      return ["Plan", "PreviousYear", "Forecast"].some(
        (role) => (qs[role]?.projections || []).length > 0);
    });
    if ((!sc.hasActual || !sc.hasComparative) && !bindsAComparison) {
      p.problems.push({
        code: "model-has-no-scenario-measures", severity: "wrong-numbers",
        location: p.model.files[0] || "the semantic model",
        message: "This model has no per-scenario measures, so a variance report is not possible: "
          + "`Values` and `Plan` are separate wells and need separate fields. Every variance and "
          + "prior-year column will be empty or meaningless while the page still looks finished. "
          + "Add measures per scenario, for example AC, PL and PY.",
      });
    }
    // Only a model that computes prior year with time intelligence can suffer the fault this rule
    // describes. See the note in tmdl.dateTable -- 8 of 20 shipped templates fired, and at least two
    // of them use no time-intelligence function at all.
    // REWORDED 2026-08-05, and demoted from `wrong-numbers`. The old message ended "prior year
    // equals actual, the delta reads a flat 0.0%, and nothing on screen says so" -- a real,
    // measured symptom BORROWED FROM A DIFFERENT FAULT. The skill and the held catalogue both attribute
    // PY ≡ AC to no time context in the visual's grouping or filter, not to an unmarked table.
    // Marking is genuinely best practice, and DATEADD or SAMEPERIODLASTYEAR against a contiguous
    // date column still computes without it -- which is what the four remaining shipped templates
    // do, correctly. So this is a risk note, not a detected defect, and it says so.
    if (!dt.marked && dt.usesTimeIntelligence) {
      p.problems.push({
        code: "no-date-table-marked", severity: "looks-fine",
        location: dt.candidate ? `${dt.candidate} (not marked)` : "the semantic model",
        message: "This model computes prior year or year-to-date, but no table is marked as the "
          + "date table — `dataCategory: Time` plus a key column. Time intelligence against a "
          + "contiguous date column still computes without it, so this is not proof of a wrong "
          + "number. It does leave Power BI free to build its own auto date/time hierarchy "
          + "alongside yours, and a visual that groups on the wrong one of the two is wrong "
          + "while looking right. Mark it."
          + (dt.candidate ? ` \`${dt.candidate}\` looks like the intended calendar.` : ""),
      });
    }
  }

  return p;
}

// --- the tool -----------------------------------------------------------------------------

/**
 * The mechanical half of planning. Resolves the project, then enumerates it.
 *
 * Deliberately shares `resolveProject` with `validate_report`: an enumeration computed from a
 * different read of the project than the validator uses is an enumeration that can disagree with
 * it, and two instruments disagreeing silently is this project's most expensive failure class.
 */
function profileProjectTool(args) {
  const projectPath = args && args.projectPath;
  if (typeof projectPath !== "string" || !projectPath) {
    return { ok: false, error: "projectPath is required and must be a string" };
  }
  const p = resolveProject(projectPath);
  if (!p || p.fatal) {
    return { ok: false, error: (p && p.fatal) || "the project could not be read" };
  }
  return prof.profileProject(p);
}

function validateReport(args) {
  const projectPath = args && args.projectPath;
  const rules = loadRules();

  if (rules === null) {
    return {
      ok: false,
      error:
        "The rule catalogue is missing or unreadable, so nothing was checked. This is a broken " +
        "install rather than a clean report. Reinstall the plugin.",
    };
  }

  const project = resolveProject(projectPath);
  if (project.fatal) return { ok: false, error: project.fatal };

  const findings = [...project.problems];
  const ran = [];
  const carriedNotRun = [];

  for (const rule of rules) {
    const fn = checkers[rule.check];
    if (!fn) { carriedNotRun.push(rule.id); continue; }
    ran.push(rule.id);
    for (const hit of fn(project)) {
      findings.push({
        code: rule.id,
        severity: rule.severity,
        location: hit.location,
        message: rule.message,
        // The per-hit detail, which was computed and then dropped here. Two checkers set it and
        // both lose their point without it: `data-role-exceeds-declared-maximum` produces
        // "3 of max 1", and the calculated-table relationship rule produces the one sentence that
        // sends the reader to the column rather than the relationship. Corrected 2026-08-31.
        ...(hit.detail ? { detail: hit.detail } : {}),
      });
    }
  }

  const severityOrder = { "wont-open": 0, blank: 1, "wrong-numbers": 2, "looks-fine": 3 };
  findings.sort((a, b) => (severityOrder[a.severity] ?? 9) - (severityOrder[b.severity] ?? 9));

  return {
    ok: true,
    findings,
    checked: project.checked,
    rulesRun: ran.length,
    // Never empty, and deliberately specific. A green result from this tool is not a claim
    // that the report is correct, and the two largest classes of Zebra defect live here.
    notChecked: [
      "Whether any number is right. Nothing here reads your data.",
      "Whether the actuals cover the same window as the comparison. A partial trailing " +
        "month produces a confident, completely wrong variance, and no file check can see it.",
      "Whether the report renders. Only a screenshot shows that.",
      ...(project.notCheckedExtra ?? []),
      ...(carriedNotRun.length
        ? [`${carriedNotRun.length} rule(s) are in the catalogue but have no checker yet.`]
        : []),
    ],
  };
}

// --- the encoder tools ----------------------------------------------------------------------
// Every entry maps a tool name to the encoder plus the schema the caller is held to. The
// required[] lists are not ceremony: each one is a landmine that becomes unreachable when the
// field cannot be omitted.

const ENCODERS = {
  encode_table_columns: {
    fn: enc.encodeTableColumns,
    description: "Encode per-column settings for a Zebra Table: order, formatting, in-cell "
      + "charts, visibility. Emits the complete key set, because omitting one renders the cells "
      + "solid black rather than falling back to a default.",
    schema: {
      type: "object",
      properties: {
        columns: { type: "array", description: "One entry per column.", items: {
          type: "object",
          properties: {
            key: { type: "string", description: "A scenario role (actual, plan, previousYear, "
              + "forecast), a comparison from encode_table_calculations, or a measure name." },
            order: { type: "number" },
            inCellChart: { type: "string", enum: ["none", "bar"] },
            bold: { type: "boolean" },
            textColor: { type: "string", description: "Plain hex, e.g. #0078D4. Inside a blob "
              + "colour is a bare hex string, not a nested literal." },
            backgroundFill: { type: "string" },
            hidden: { type: "boolean" },
            hideFromGroups: { type: "array", items: {} },
          },
          required: ["key"],
        } },
        mode: { type: "string", enum: ["table", "chart"],
          description: "Which view the styling applies to. tableView is read only when "
            + "chartSettings.showAsTable is true, chartView only when it is false." },
        legalKeys: { type: "array", items: { type: "string" },
          description: "Optional. Pass legalColumnKeys from encode_table_calculations to have "
            + "unknown keys warned about instead of silently ignored." },
      },
      required: ["columns", "mode"],
    },
  },
  encode_table_calculations: {
    fn: enc.encodeTableCalculations,
    description: "Declare which variance columns a Zebra Table has. This governs which column "
      + "keys are legal, so call it before encode_table_columns and pass its legalColumnKeys on.",
    schema: { type: "object", properties: {
      comparisons: { type: "array", items: { type: "string", enum: enc.COMPARISONS } },
    }, required: ["comparisons"] },
  },
  encode_added_formulas: {
    fn: enc.encodeAddedFormulas,
    description: "Encode computed rows for a Zebra Table: ratios and subtotals in the report "
      + "layer, no DAX. Returns the exclusion blob alongside, because a computed row is summed "
      + "into the grand total unless it is excluded and the wrong total looks entirely right.",
    schema: { type: "object", properties: {
      categoryField: { type: "string", description: "e.g. 'Accounts.Account group'" },
      formulas: { type: "array", items: { type: "object", properties: {
        name: { type: "string", description: "The row label. Later formulas can reference it." },
        expression: { type: "string", description: "e.g. '[Gross profit] / [Revenue]'. "
          + "References category names, not DAX." },
        aggregatesOtherRows: { type: "boolean", description: "True if this row sums or derives "
          + "from other rows. Required, because it decides whether the row is kept out of the "
          + "grand total." },
        insertAfter: { type: "string" }, bold: { type: "boolean" }, italic: { type: "boolean" },
        percent: { type: "boolean" }, decimalPlaces: { type: "number" },
        units: { type: "string", enum: ["P", "Auto", "Default"] }, fontColor: { type: "string" },
      }, required: ["name", "expression", "aggregatesOtherRows"] } },
    }, required: ["categoryField", "formulas"] },
  },
  encode_annotations: {
    fn: enc.encodeAnnotations,
    description: "Encode the comment layer for a Zebra Table. currentFilters is required: a "
      + "comment with no filter-context key blanks the ENTIRE visual, and one pinned to a state "
      + "the page cannot reach is invisible forever.",
    schema: { type: "object", properties: {
      valuesOrder: { type: "array", items: { type: "string" },
        description: "The Values projections in binding order." },
      currentFilters: { type: "array", items: { type: "object", properties: {
        fieldName: { type: "string" }, queryName: { type: "string" }, value: {},
      }, required: ["fieldName", "queryName", "value"] },
        description: "The LIVE filter state the page will be in when the comment should show." },
      comments: { type: "array", items: { type: "object", properties: {
        cell: { type: "object", properties: {
          category: { description: "The row." }, group: { description: "The group, if bound." },
          column: { type: "string", description: "A name from valuesOrder." },
        }, required: ["category", "column"],
          description: "Where the bubble sits. Omit it and pass highlightId instead to attach "
            + "the comment to a highlight from encode_highlights." },
        highlightId: { type: "string", description: "A uuid from encode_highlights' ids map; the "
          + "shape then owns the position and no cell is given." },
        text: { description: "A string, or [{text, bold?, italic?}] for rich text." },
      }, required: ["text"] } },
      timestamp: { type: "string", description: "Optional ISO stamp. Defaults to a fixed value "
        + "so re-encoding the same input does not churn the file." },
      target: { type: "string", enum: ["tables", "charts"],
        description: "Which product the comment layer is being written for. The blob shape "
          + "differs, and the Table shape on a Chart drops every comment." },
      categoryFields: { type: "array", items: { type: "string" },
        description: "Charts only, and required there: the bound category field, e.g. ['Year'], "
          + "or one entry per level on a hierarchy. Omit on Tables." },
    }, required: ["currentFilters", "comments", "target"] },
  },
  encode_highlights: {
    fn: enc.encodeHighlights,
    description: "Draw a rectangle or an ellipse over cells of a Zebra Table "
      + "(annotationLayerSettings.annotationHighlights), optionally to hang a comment on. Writes "
      + "the two context keys whose absence blanks the WHOLE visual, and refuses a column whose "
      + "index has not been measured rather than guessing it. Returns ids to pass as highlightId "
      + "to encode_annotations.",
    schema: { type: "object", properties: {
      columns: { type: "array", items: {}, description: "The table's scenario columns in "
        + "left-to-right display order: names from actual / plan / previousYear / forecast / "
        + "actual-<cmp> / actual-<cmp>-percent, or {name, index} read from a Desktop-saved visual "
        + "for anything beyond one comparison." },
      sortByColumn: { type: "string", description: "Default 'actual'." },
      sortDirection: { type: "number", enum: [0, 1], description: "Default 1." },
      currentFilters: { type: "array", items: { type: "object", properties: {
        fieldName: { type: "string" }, queryName: { type: "string" }, value: {},
      }, required: ["fieldName", "queryName", "value"] },
        description: "The LIVE filter state the page will be in." },
      highlights: { type: "array", items: { type: "object", properties: {
        shape: { type: "string", enum: ["rectangle", "ellipse"] },
        rows: { type: "array", items: {}, description: "Category members, or {category, group}." },
        columns: { type: "array", items: { type: "string" }, description: "Names from columns." },
        id: { type: "string", description: "Your own key for the ids map; optional." },
      }, required: ["rows", "columns"] } },
    }, required: ["columns", "currentFilters", "highlights"] },
  },
  encode_cagr_arrows: {
    fn: enc.encodeCagrArrows,
    description: "A growth arrow across a Zebra Chart series "
      + "(annotationLayerSettings.annotationCagrArrows). No data anchor; filterContexts written. "
      + "The number compounds per category step, so name the period in the label on anything but "
      + "a yearly axis.",
    schema: { type: "object", properties: {
      currentFilters: { type: "array", items: { type: "object", properties: {
        fieldName: { type: "string" }, queryName: { type: "string" }, value: {},
      }, required: ["fieldName", "queryName", "value"] } },
      arrows: { type: "array", items: { type: "object", properties: {
        label: { type: "string", description: "Free text, rendered verbatim. Default 'CAGR'." },
        lineWidth: { type: "number" }, color: { type: "string" },
        lineStyle: { type: "number" }, headType: { type: "number" },
      } } },
    }, required: ["currentFilters", "arrows"] },
  },
  encode_storage_config: {
    fn: enc.encodeStorageConfig,
    description: "Link a Tables+ or Charts+ visual to the SharePoint or OneDrive Excel workbook "
      + "that holds its view-mode comments (annotationLayerSettings.annotationsStorageConfig). "
      + "Viewers with access to that workbook then see, add and edit comments in view mode, and "
      + "an agent that can write the workbook can place comments itself. The workbook needs an "
      + "'Annotation' sheet with one table headed UUID, Type, Tenant ID, User ID, User Name, "
      + "Content, CreatedAt, UpdatedAt, Status; Content is the same JSON encode_annotations "
      + "emits per comment. Nothing checks the path before the visual loads.",
    schema: { type: "object", properties: {
      siteId: { type: "string", description: "The SharePoint site COLLECTION GUID. Omit when "
        + "passing driveId." },
      driveId: { type: "string", description: "A Graph drive id (starts with b!) from any Graph "
        + "search result; the site GUID is derived from it." },
      folderPath: { type: "string", description: "'/drive/root:' for the library root, or "
        + "'/drive/root:/Folder/Sub'. No trailing slash." },
      fileName: { type: "string", description: "The workbook's file name, ending in .xlsx." },
    }, required: ["folderPath", "fileName"] },
  },
  plan_card_invert: {
    fn: enc.planCardInvert,
    description: "Step one of inverting individual Zebra Cards. Card ids are minted by Power BI "
      + "Desktop and cannot be computed, so this returns the procedure rather than a blob.",
    schema: { type: "object", properties: {
      cardsToInvert: { type: "array", items: { type: "string" } },
    }, required: ["cardsToInvert"] },
  },
  encode_card_invert: {
    fn: enc.encodeCardInvert,
    description: "Step two: encode per-card inversion using the ids Desktop minted. Card SIZE is "
      + "not settable here; an authored size with no cards is accepted and silently ignored.",
    schema: { type: "object", properties: {
      cardIds: { type: "array", items: { type: "object", properties: {
        id: { type: "string", description: "Read back from the saved report." },
        invert: { type: "boolean" },
      }, required: ["id", "invert"] } },
      instance: { type: "number" },
    }, required: ["cardIds"] },
  },
  encode_data_value_list: {
    fn: enc.encodeDataValueList,
    description: "Encode the properties that hold a plain list of data values: result rows, "
      + "highlighted categories, inverted groups, collapsed groups.",
    schema: { type: "object", properties: {
      target: { type: "string", enum: Object.keys(enc.LIST_TARGETS) },
      values: { type: "array", items: {}, description: "Literal data values off the binding, "
        + "exactly as they appear. Newlines included; do not pre-escape them." },
    }, required: ["target", "values"] },
  },
  encode_category_scenarios: {
    fn: enc.encodeCategoryScenarios,
    description: "Mark individual CATEGORY VALUES of a Zebra Chart as forecast so a build-up "
      + "renders solid actuals and hatched projected steps on ONE series "
      + "(categoriesMetadata.scenarios + results + floatingResults + highlighted). Use this, not "
      + "the Forecast role, for a pipeline or a plan bridge whose later steps are projections: "
      + "binding Forecast makes the chart bridge total forecast down to actual. Keys are data "
      + "values and break silently when the data changes. Only forecast (3) is render-confirmed.",
    schema: { type: "object", properties: {
      scenarios: { type: "object", additionalProperties: {},
        description: "Category value -> 'forecast' (or 3). One entry per hatched step." },
      results: { type: "array", items: {}, description: "Every category value in the build-up "
        + "in draw order, anchors and steps; the first is normally the banked total." },
      floating: { type: "array", items: {}, description: "The subset of results that read as "
        + "components of the build-up (no good/bad colour). Usually the projected steps." },
      highlighted: { type: "array", items: {}, description: "Category values to highlight; "
        + "usually omitted." },
    }, required: ["scenarios", "results"] },
  },
};

// --- the writer tools -------------------------------------------------------------------------
// Same dispatch shape as the encoders: a function that either returns an answer or throws an
// EncodeError whose message names the field and says what it prevents.
//
// The schema IS the documentation. An agent has to be able to drive these without reading prose,
// so the descriptions carry the format facts a caller cannot guess: which literal form each value
// type produces, why a property group is never written unattended, and what is deliberately not
// written at all.

/** The escape hatch, described once and referenced from the visual, page and container schemas. */
const PROPERTY_MAP_DESC =
  "Arbitrary properties as a map of 'objectGroup.propertyName' to a value. This is the main road, "
  + "not a side door: roughly 200 distinct property paths are needed to reproduce 90% of real "
  + "files, so most of what you author arrives here. The VALUE decides the PBIR literal form — "
  + "number 3 becomes 3D (never '3', which is not a declared enum value and is dropped in "
  + "silence, leaving the visual on its default); true/false become bare tokens; a string becomes "
  + "'quoted'; {\"__literal\":\"2L\"} is written raw for the L-suffix and anything else; "
  + "{\"__solid\":\"#1A1A2E\"} produces the nested colour wrapper used by fontColor; "
  + "{\"__json\":{...}} is serialised then quoted, for a blob no encoder covers; "
  + "{\"__raw\":{...}} is the whole value verbatim, for a property that is not a PBIR literal at "
  + "all, such as a textbox's general.paragraphs. Only the groups "
  + "you name are written — no group is present in 90% of real files, so there is no default "
  + "layer. licenseSettings, license, version, visualCreatedVersion, migrationLog and "
  + "previewSettings are REFUSED: that is telemetry the visual writes about itself, and a licence "
  + "key in a report file is a credential.";

const VISUAL_SPEC_SCHEMA = {
  type: "object",
  properties: {
    name: { type: "string", description: "The visual id, and the visuals/<name>/ directory name. "
      + "Letters, digits, underscore and hyphen only." },
    visualType: { type: "string", description: "A GUID, or an alias: 'tables+' and 'charts+' (the "
      + "Plus track, the default for new reports), 'cards', 'tables' and 'charts' (certified), or "
      + "'tables-appsource' / 'charts-appsource' / 'cards-appsource' for the older GUIDs found "
      + "inside file-imported reports. Any other string is written through with a warning, which "
      + "is how a slicer or a textbox gets onto the page." },
    position: { type: "object", description: "x, y, width and height are required. z defaults to "
      + "0. tabOrder is NOT derived from z — they are paint order and keyboard order, identical in "
      + "only 58.8% of real files — so it is written only when you give it.",
      properties: { x: { type: "number" }, y: { type: "number" }, width: { type: "number" },
        height: { type: "number" }, z: { type: "number" }, tabOrder: { type: "number" } },
      required: ["x", "y", "width", "height"] },
    bindings: { type: "object", description: "Data roles to projections. Roles: Category and Group "
      + "(grouping), Values, Plan, PreviousYear, Forecast, Filters, Tooltips. Each entry is "
      + "'Entity.Property' — split on the LAST dot, so '.Measures.AC' is entity '.Measures' — or "
      + "{entity, property, kind?, displayName?, active?}. kind defaults from the role: Column for "
      + "Category and Group, Measure for everything else, measured at 100% both ways across 270 "
      + "corpus visuals. queryRef and nativeQueryRef are derived." },
    title: { description: "A string, or {text, show}. Sugar for titleSettings. Zebra titles accept "
      + "[Measure] tokens, which the visual resolves at render." },
    properties: { type: "object", description: PROPERTY_MAP_DESC },
    tableCalculations: { type: "object", description: "Routes to encode_table_calculations: which "
      + "variance columns the Table has. Its legal column keys are handed to tableColumns "
      + "automatically when both are in one spec.",
      properties: { comparisons: { type: "array", items: { type: "string" } } } },
    tableColumns: { type: "object", description: "Routes to encode_table_columns: per-column "
      + "order, formatting, in-cell charts and visibility. Needs mode ('table' or 'chart') and "
      + "columns[]. This blob is 45.0% of all author-chosen bytes in real files." },
    addedFormulas: { type: "object", description: "Routes to encode_added_formulas: computed rows "
      + "in the report layer, no DAX. Returns its grand-total exclusion blob alongside." },
    annotations: { type: "object", description: "Routes to encode_annotations: the comment layer, "
      + "20.8% of author-chosen bytes. currentFilters is mandatory there — an absent "
      + "filterContexts key blanks the ENTIRE visual." },
    cardInvert: { type: "object", description: "Routes to encode_card_invert. The only way to "
      + "reach customData: card ids are minted by Power BI Desktop and cannot be computed, so run "
      + "plan_card_invert first and read the ids back out of a saved report." },
    dataValueLists: { type: "array", description: "Routes to encode_data_value_list, one entry per "
      + "target: result rows, highlighted categories, inverted groups, collapsed groups.",
      items: { type: "object" } },
    visualContainerObjects: { type: "object", description: "Container-level chrome outside the "
      + "Zebra property space, as the same 'group.property' map. Almost always {'title.show': "
      + "false}, turning the Power BI title bar off because the Zebra title is inside the visual." },
    filterConfig: { description: "Visual-level filters, passed through verbatim. Not modelled: a "
      + "filter's `name` is a 20-hex-digit id with no derivation rule. This is the one part of a "
      + "visual that is not compressed at all." },
    rawObjects: { type: "object", description: "Whole object groups passed through verbatim, as "
      + "objectGroup to the raw entry array. For a group this writer has no model for: more than "
      + "one entry, a `selector` beside the properties, or a shape a future schema introduces. "
      + "Still refused for the never-emit groups — a passthrough that skipped that check would be "
      + "the one door left open to a licence key." },
    queryExtras: { type: "object", description: "Siblings of queryState inside visual.query — "
      + "`sortDefinition`, which is how a visual's own sort is authored, and `isDrillDisabled`. "
      + "Passed through verbatim." },
    visualExtras: { type: "object", description: "Any other key on `visual`, e.g. expansionStates. "
      + "Passed through verbatim." },
    drillFilterOtherVisuals: { type: "boolean", description: "Written only when given. 248 of 270 "
      + "corpus visuals carry it and 22 do not, so it is not invented for you." },
    schemaVersion: { type: "string", description: "visualContainer schema. Defaults to 2.11.0, "
      + "which is what current Desktop writes; 2.8.0 and 2.10.0 also occur." },
  },
  required: ["name", "visualType", "position"],
};

const PAGE_SPEC_PROPERTIES = {
  name: { type: "string", description: "The page id and its pages/<name>/ directory. Not what the "
    + "user sees — that is displayName." },
  displayName: { type: "string", description: "The tab label." },
  width: { type: "number", description: "Defaults to 1280." },
  height: { type: "number", description: "Defaults to 720." },
  displayOption: { type: "string", description: "Defaults to FitToPage." },
  type: { type: "string", description: "'Tooltip' makes this a canvas tooltip page. Needs page "
    + "schema 2.x; a 1.x schema cannot express it and the page silently stops being one." },
  visibility: { type: "string" },
  pageBinding: { type: "object" },
  visualInteractions: {},
  properties: { type: "object", description: PROPERTY_MAP_DESC },
  filterConfig: { description: "Page-level filters, passed through verbatim." },
  schemaVersion: { type: "string", description: "page schema. Defaults to 2.1.0." },
  visuals: { type: "array", description: "The visuals on this page.", items: VISUAL_SPEC_SCHEMA },
};

const WRITERS = {
  write_visual: {
    fn: wr.writeVisual,
    description: "Write a complete Zebra BI visual.json from a spec, instead of hand-emitting the "
      + "file. Returns the file content as a string plus its byte count and the spec's, so the "
      + "compression is measured rather than assumed — expect roughly 4.5-6x on a typical visual "
      + "and about 1x on one dominated by a passthrough filterConfig or a large comment blob. "
      + "Blobs are built by the encoder tools, never re-derived here. Nothing is written to disk. "
      + "Run validate_report over the finished project afterwards: this writes what you ask for "
      + "and does not check whether you asked for the right thing.",
    schema: VISUAL_SPEC_SCHEMA,
  },
  write_page: {
    fn: wr.writePage,
    description: "Write a page.json and every visual.json on it in one call. Returns a map of "
      + "path to content, with paths relative to the .Report directory "
      + "(definition/pages/<name>/…), so a page written on its own and a page written as part of "
      + "a report land in the same place. Nothing is written to disk.",
    schema: {
      type: "object",
      properties: PAGE_SPEC_PROPERTIES,
      required: ["name", "displayName"],
    },
  },
  write_report: {
    fn: wr.writeReport,
    description: "Write the whole definition/pages tree — pages.json, every page directory and "
      + "every visual directory — as one map of path to content. Replaces twenty-odd sequential "
      + "hand-written files with a single call. What it does NOT write comes back in notWritten, "
      + "and that list matters: report.json carries the base theme, and a report with no base "
      + "theme renders NOTHING with no error anywhere. Nothing is written to disk.",
    schema: {
      type: "object",
      properties: {
        pages: { type: "array", description: "The pages, in tab order.",
          items: { type: "object", properties: PAGE_SPEC_PROPERTIES,
                   required: ["name", "displayName"] } },
        activePageName: { type: "string", description: "Defaults to the first page." },
        pagesSchemaVersion: { type: "string", description: "pagesMetadata schema. Defaults to "
          + "1.1.0, which is the pageOrder form. The older pages[]-with-ordinal form is not "
          + "emitted." },
      },
      required: ["pages"],
    },
  },
};

/** Everything reachable through tools/call that is not validate_report. */
const CALLABLE = { ...ENCODERS, ...WRITERS };

const TOOLS = [
  {
    name: "validate_report",
    description:
      "Check an unopened Power BI project (.pbip) for faults that render blank, wrong or " +
      "not at all. Returns what was checked, what was found, and what it could not see.",
    inputSchema: {
      type: "object",
      properties: {
        projectPath: {
          type: "string",
          description: "Absolute path to the folder holding the .pbip file.",
        },
      },
      required: ["projectPath"],
    },
  },
  {
    name: "propose_pages",
    description:
      "Turn the ranked enumeration into a write_report spec: one page per high-signal dimension, " +
      "in ranked order, using the house pattern. Runs profile_project internally, so it needs " +
      "rows on disk (a DATATABLE partition) or it refuses rather than proposing from an unranked " +
      "list. Returns the spec plus the numbers that justified each page, so a page can be thrown " +
      "out on sight. It does NOT decide what the report says, does not name a story, and will NOT " +
      "invent a comparison: with no AC/PL/PY pair it emits value-only pages and says so, because " +
      "a variance column with nothing valid behind it is worse than no column. Everything it " +
      "refused to decide is in youMustStillDecide; skipped dimensions are in notProposed.",
    inputSchema: {
      type: "object",
      properties: {
        projectPath: { type: "string", description: "Absolute path to the folder holding the .pbip." },
        maxPages: { type: "number", description: "Default 4. One page per distinct dimension." },
        usePlus: { type: "boolean", description: "Default true — Tables+ is the authoring default." },
      },
      required: ["projectPath"],
    },
  },
  {
    name: "profile_project",
    description:
      "Enumerate what a model can be asked, BEFORE choosing a story. Returns every table, every " +
      "measure, and every candidate dimension — including the categorical columns on the fact " +
      "table itself, which are the ones a hand-written list misses because they are not in the " +
      "relationship diagram. Where rows are embedded (a DATATABLE partition) it also returns real " +
      "cardinality, ranges and members. Reports the ENUMERATION DENOMINATOR (usable dimensions × " +
      "measures = candidate questions) so the completeness gate has a number to be a fraction of, " +
      "flags a cardinality-1 dimension as a finding rather than a filter, names structural " +
      "gaps (no date column, no plan/PY measure), and where rows are on disk RANKS the candidate " + "questions by measured effect so you review a ranked list instead of deriving one — tautological " + "pairs (a band vs the column it was cut from) are excluded with the reason. It reads FILES: it " + "ranks COLUMNS not measures, does not evaluate a measure, " +
      "does not check period coverage, and cannot tell you which questions carry signal — those " +
      "are listed in notProfiled. Run it before planning; it replaces the hand-written list, not " +
      "the judgement about what the report should say.",
    inputSchema: {
      type: "object",
      properties: {
        projectPath: {
          type: "string",
          description: "Absolute path to the folder holding the .pbip file.",
        },
      },
      required: ["projectPath"],
    },
  },
  {
    name: "profile_source",
    description:
      "The analyst's first hour on a folder of flat files, done mechanically and BEFORE a model " +
      "exists. Reads CSV / pipe / tab / semicolon text and JSON arrays (not workbooks or parquet — " +
      "those are named in notProfiled), sniffs the delimiter, classifies each file (fact, " +
      "dimension, date, scenario), finds the joins and counts orphan keys, and then reports what " +
      "a seasoned analyst checks before trusting a source: the FISCAL YEAR from the date table " +
      "(which month it starts, whether it is named by its start or end year, and whether the " +
      "source's own column is even consistent), coverage per period with the trailing stub and " +
      "the LAST COMPLETE PERIOD, posting dates that drift around month end, future-dated rows, " +
      "scenario coverage (declared-but-empty scenarios, the plan's window and how many entities " +
      "it reaches, plan and prior year that never overlap), the sign convention of the amounts, " +
      "parent-child hierarchies and their roll-up operator, point-in-time columns that must not " +
      "be summed, mixed currency with or without a rate table, consolidation ownership below " +
      "100%, and duplicate rows. Returns analystBrief — the assumptions to write into the plan and " +
      "repeat in the delivery, one line each — plus gaps and notProfiled. It does NOT evaluate a " +
      "measure, decide what the report says, or read binary files.",
    inputSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Absolute path to a folder of flat files (walked two levels deep), or to one file.",
        },
      },
      required: ["path"],
    },
  },
];

// --- JSON-RPC over stdio --------------------------------------------------------------------

function respond(id, result) {
  process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id, result }) + "\n");
}
function respondError(id, code, message) {
  process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id, error: { code, message } }) + "\n");
}

function handle(msg) {
  const { id, method, params } = msg;
  // A notification has no id and takes no reply. Answering one is a protocol error.
  if (id === undefined || id === null) return;

  switch (method) {
    case "initialize":
      return respond(id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: SERVER,
      });
    case "tools/list":
      return respond(id, { tools: [...TOOLS, ...Object.entries(CALLABLE).map(([name, e]) => ({
        name, description: e.description, inputSchema: e.schema,
      }))] });
    case "tools/call": {
      const name = params && params.name;
      if (CALLABLE[name]) {
        try {
          const result = CALLABLE[name].fn(params.arguments || {});
          return respond(id, {
            content: [{ type: "text", text: JSON.stringify(result, null, 2) }], isError: false,
          });
        } catch (err) {
          // A refused encode is a useful answer, not a crash: the message names the field and
          // says what it prevents, so the caller can fix the call rather than guess.
          return respond(id, {
            content: [{ type: "text", text: JSON.stringify(
              { ok: false, error: String(err && err.message) }, null, 2) }], isError: true,
          });
        }
      }
      if (name === "propose_pages") {
        const a = params.arguments || {};
        const pr = resolveProject(a.projectPath);
        const out = (!pr || pr.fatal)
          ? { ok: false, error: (pr && pr.fatal) || "the project could not be read" }
          : propose.proposePages(prof.profileProject(pr), a);
        return respond(id, {
          content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
          isError: out.ok === false,
        });
      }
      if (name === "profile_project") {
        const out = profileProjectTool(params.arguments || {});
        return respond(id, {
          content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
          isError: out.ok === false,
        });
      }
      if (name === "profile_source") {
        const out = profSource.profileSource(params.arguments || {});
        return respond(id, {
          content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
          isError: out.ok === false,
        });
      }
      if (name !== "validate_report") {
        return respondError(id, -32601, `Unknown tool: ${name}`);
      }
      const out = validateReport(params.arguments || {});
      return respond(id, {
        content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
        isError: !out.ok,
      });
    }
    case "ping":
      return respond(id, {});
    default:
      return respondError(id, -32601, `Method not found: ${method}`);
  }
}

// Only listen when run as the server. `require`ing this module for its checkers must not
// attach a stdin listener, which keeps the event loop alive and hangs the caller forever.
function listen() {
let buffer = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  buffer += chunk;
  let nl;
  while ((nl = buffer.indexOf("\n")) !== -1) {
    const line = buffer.slice(0, nl).trim();
    buffer = buffer.slice(nl + 1);
    if (!line) continue;
    let msg;
    try { msg = JSON.parse(line); } catch { continue; }
    try { handle(msg); } catch (err) {
      if (msg && msg.id != null) respondError(msg.id, -32603, String(err && err.message));
    }
  }
});

}

if (require.main === module) listen();

module.exports = { validateReport, resolveProject, checkers, loadRules, listen,
                   ENCODERS, WRITERS, CALLABLE, TOOLS, profileProjectTool,
                   profileSourceTool: profSource.profileSource };
